import React, { FC } from 'react'

import InstallPWA from '../components/InstallPWA'

export const Home: FC = () => {
  return (
    <section className='container pt5'>
      <div className='textCenter mb5'>
        <h1>React Project Skeleton, Default Version</h1>
        <p>
          App generated by using:
          <strong className='backgroundPrimary textDefault px1 ml1'>
            create-react-app --template pi
          </strong>
        </p>
        <InstallPWA />
      </div>
    </section>
  )
}
